service: pp-planner-tst

env:
  clear:
    PP_HST: '<%= ENV["PP_HOSTNAME_DB_TST"] %>'
    PP_USR: '<%= ENV["PP_USR_TST"] %>'
    API_URL: <%= ENV["VITE_API_BASE_URL_TST"] %>
    API_HOST: <%= ENV["PP_LINK_API_TST"] %>
    PP_DB_HOST: <%= ENV["PP_HOSTNAME_DB_TST"] %>
    PP_DB_PORT: <%= ENV["PP_PORT_API"] %>

# Deploy to these servers.
servers:
  web:
    hosts:
      - '<%= ENV["PP_HOSTNAME_SSH_TST"] %>'

ssh:
  user: '<%= ENV["PP_USR_SSH_TST"] %>'

# dev: no TLS; unique proxy host to avoid conflicts with prod
proxy:
  host: tst-planner.lan
  ssl: false
  app_port: <%= ENV["PP_PORT_API"] %>
  healthcheck:
    path: /up
    timeout: 10
    interval: 2

builder:
  arch: amd64
  remote: 'ssh://<%= ENV["PP_USR_SSH_TST"] %>@<%= ENV["PP_HOSTNAME_SSH_TST"] %>'
