@startsalt
{
  {^"Fixture-row"
    The fixture-row goes here
  }
  {^"Match details"
    _         | Team 1          | Team 2
    Name      | ^Team1 name   ^ | ^Team2 name   ^
    Goals/Points     | { " 0" | " 0"} | { " 0" | " 0" }
  }
  [ Update Score ] | [ Cancel ]

  {^"Adjust fixture"
    On pitch     | ^Current pitch selected ^
    Action       | ^Place after^
    Relative to  | ^Select target fixture...^
  }
  [ Update Schedule ] | [ Cancel ]
}
@endsalt 
